FROM baijunyao/php:8.0

RUN docker-php-ext-install pcntl \
    && pecl install -o -f xdebug \
    && cp /usr/local/etc/php/php.ini-development /usr/local/etc/php/php.ini \
    && printf '%s\n' 'post_max_size=20M' 'upload_max_filesize=20M' 'max_input_vars=10000' 'max_execution_time=300' >> /usr/local/etc/php/php.ini \
    && composer config -g repo.packagist composer https://mirrors.aliyun.com/composer/

COPY conf/docker-php-ext-xdebug.ini /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
