FROM baijunyao/php:7.3

RUN docker-php-ext-install pcntl \
    && pecl install -o -f xdebug \
    && cp /usr/local/etc/php/php.ini-development /usr/local/etc/php/php.ini

COPY conf/docker-php-ext-xdebug.ini /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
