FROM baijunyao/php:7.4

RUN docker-php-ext-install opcache \
    && cp /usr/local/etc/php/php.ini-production /usr/local/etc/php/php.ini \
    && printf '%s\n' 'post_max_size=20M' 'upload_max_filesize=20M' >> /usr/local/etc/php/php.ini
