name: AliyunContainerRegistry

on: [push]

jobs:
  ubuntu:
    name: Ubuntu
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - uses: azure/docker-login@v1
        with:
          login-server: registry.cn-beijing.aliyuncs.com
          username: ${{ secrets.ALIYUN_CONTAINER_REGISTRY_USERNAME }}
          password: ${{ secrets.ALIYUN_CONTAINER_REGISTRY_PASSWORD }}
      - name: Ubuntu Bionic
        run: |
          docker build -f ubuntu/bionic/Dockerfile -t registry.cn-beijing.aliyuncs.com/baijunyao/ubuntu:bionic ubuntu/bionic/
          docker push registry.cn-beijing.aliyuncs.com/baijunyao/ubuntu:bionic
      - name: Ubuntu Focal
        run: |
          docker build -f ubuntu/focal/Dockerfile -t registry.cn-beijing.aliyuncs.com/baijunyao/ubuntu:focal ubuntu/focal/
          docker push registry.cn-beijing.aliyuncs.com/baijunyao/ubuntu:focal
  alpine:
    name: Alpine
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - uses: azure/docker-login@v1
        with:
          login-server: registry.cn-beijing.aliyuncs.com
          username: ${{ secrets.ALIYUN_CONTAINER_REGISTRY_USERNAME }}
          password: ${{ secrets.ALIYUN_CONTAINER_REGISTRY_PASSWORD }}
      - name: Ubuntu Bionic
        run: |
          docker build -f alpine/3.12/Dockerfile -t registry.cn-beijing.aliyuncs.com/baijunyao/alpine:3.12 alpine/3.12/
          docker push registry.cn-beijing.aliyuncs.com/baijunyao/alpine:3.12
  mysql-client:
    name: MySQL Client
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - uses: azure/docker-login@v1
        with:
          login-server: registry.cn-beijing.aliyuncs.com
          username: ${{ secrets.ALIYUN_CONTAINER_REGISTRY_USERNAME }}
          password: ${{ secrets.ALIYUN_CONTAINER_REGISTRY_PASSWORD }}
      - name: MySQL Client
        run: |
          docker build -f mysql-client/1.1/Dockerfile -t registry.cn-beijing.aliyuncs.com/baijunyao/mysql-client:1.1 mysql-client/1.1/
          docker push registry.cn-beijing.aliyuncs.com/baijunyao/mysql-client:1.1
  nginx:
    name: NGINX
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - uses: azure/docker-login@v1
        with:
          login-server: registry.cn-beijing.aliyuncs.com
          username: ${{ secrets.ALIYUN_CONTAINER_REGISTRY_USERNAME }}
          password: ${{ secrets.ALIYUN_CONTAINER_REGISTRY_PASSWORD }}
      - name: NGINX 1.7
        run: |
          docker build -f nginx/1.7/Dockerfile -t registry.cn-beijing.aliyuncs.com/baijunyao/nginx:1.7 nginx/1.7/
          docker push registry.cn-beijing.aliyuncs.com/baijunyao/nginx:1.7
      - name: NGINX 1.19
        run: |
          docker build -f nginx/1.19/Dockerfile -t registry.cn-beijing.aliyuncs.com/baijunyao/nginx:1.19 nginx/1.19/
          docker push registry.cn-beijing.aliyuncs.com/baijunyao/nginx:1.19
  mysql:
    name: MySQL
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - uses: azure/docker-login@v1
        with:
          login-server: registry.cn-beijing.aliyuncs.com
          username: ${{ secrets.ALIYUN_CONTAINER_REGISTRY_USERNAME }}
          password: ${{ secrets.ALIYUN_CONTAINER_REGISTRY_PASSWORD }}
      - name: MySQL 8.0 local
        run: |
          docker build -f mysql/8.0/Dockerfile.local -t registry.cn-beijing.aliyuncs.com/baijunyao/mysql:8.0-local mysql/8.0/
          docker push registry.cn-beijing.aliyuncs.com/baijunyao/mysql:8.0-local
      - name: MySQL 8.0 production
        run: |
          docker build -f mysql/8.0/Dockerfile.production -t registry.cn-beijing.aliyuncs.com/baijunyao/mysql:8.0-production mysql/8.0/
          docker push registry.cn-beijing.aliyuncs.com/baijunyao/mysql:8.0-production
      - name: MySQL 5.7 local
        run: |
          docker build -f mysql/5.7/Dockerfile.local -t registry.cn-beijing.aliyuncs.com/baijunyao/mysql:5.7-local mysql/5.7/
          docker push registry.cn-beijing.aliyuncs.com/baijunyao/mysql:5.7-local
      - name: MySQL 5.7 production
        run: |
          docker build -f mysql/5.7/Dockerfile.production -t registry.cn-beijing.aliyuncs.com/baijunyao/mysql:5.7-production mysql/5.7/
          docker push registry.cn-beijing.aliyuncs.com/baijunyao/mysql:5.7-production
      - name: MySQL 5.6 local
        run: |
          docker build -f mysql/5.6/Dockerfile.local -t registry.cn-beijing.aliyuncs.com/baijunyao/mysql:5.6-local mysql/5.6/
          docker push registry.cn-beijing.aliyuncs.com/baijunyao/mysql:5.6-local
      - name: MySQL 5.6 production
        run: |
          docker build -f mysql/5.6/Dockerfile.production -t registry.cn-beijing.aliyuncs.com/baijunyao/mysql:5.6-production mysql/5.6/
          docker push registry.cn-beijing.aliyuncs.com/baijunyao/mysql:5.6-production
  php:
    name: PHP
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - uses: azure/docker-login@v1
        with:
          login-server: registry.cn-beijing.aliyuncs.com
          username: ${{ secrets.ALIYUN_CONTAINER_REGISTRY_USERNAME }}
          password: ${{ secrets.ALIYUN_CONTAINER_REGISTRY_PASSWORD }}
      - name: PHP 7.2 base
        run: |
          docker build -f php/7.2/Dockerfile -t registry.cn-beijing.aliyuncs.com/baijunyao/php:7.2 php/7.2/
          docker push registry.cn-beijing.aliyuncs.com/baijunyao/php:7.2
      - name: PHP 7.2 local
        run: |
          docker build -f php/7.2/Dockerfile.local -t registry.cn-beijing.aliyuncs.com/baijunyao/php:7.2-local php/7.2/
          docker push registry.cn-beijing.aliyuncs.com/baijunyao/php:7.2-local
      - name: PHP 7.2 production
        run: |
          docker build -f php/7.2/Dockerfile.production -t registry.cn-beijing.aliyuncs.com/baijunyao/php:7.2-production php/7.2/
          docker push registry.cn-beijing.aliyuncs.com/baijunyao/php:7.2-production
      - name: PHP 7.3 base
        run: |
          docker build -f php/7.3/Dockerfile -t registry.cn-beijing.aliyuncs.com/baijunyao/php:7.3 php/7.3/
          docker push registry.cn-beijing.aliyuncs.com/baijunyao/php:7.3
      - name: PHP 7.3 local
        run: |
          docker build -f php/7.3/Dockerfile.local -t registry.cn-beijing.aliyuncs.com/baijunyao/php:7.3-local php/7.3/
          docker push registry.cn-beijing.aliyuncs.com/baijunyao/php:7.3-local
      - name: PHP 7.3 production
        run: |
          docker build -f php/7.3/Dockerfile.production -t registry.cn-beijing.aliyuncs.com/baijunyao/php:7.3-production php/7.3/
          docker push registry.cn-beijing.aliyuncs.com/baijunyao/php:7.3-production
      - name: PHP 7.4 base
        run: |
          docker build -f php/7.4/Dockerfile -t registry.cn-beijing.aliyuncs.com/baijunyao/php:7.4 php/7.4/
          docker push registry.cn-beijing.aliyuncs.com/baijunyao/php:7.4
      - name: PHP 7.4 local
        run: |
          docker build -f php/7.4/Dockerfile.local -t registry.cn-beijing.aliyuncs.com/baijunyao/php:7.4-local php/7.4/
          docker push registry.cn-beijing.aliyuncs.com/baijunyao/php:7.4-local
      - name: PHP 7.4 production
        run: |
          docker build -f php/7.4/Dockerfile.production -t registry.cn-beijing.aliyuncs.com/baijunyao/php:7.4-production php/7.4/
          docker push registry.cn-beijing.aliyuncs.com/baijunyao/php:7.4-production
      - name: PHP 8.0 base
        run: |
          docker build -f php/8.0/Dockerfile -t registry.cn-beijing.aliyuncs.com/baijunyao/php:8.0 php/8.0/
          docker push registry.cn-beijing.aliyuncs.com/baijunyao/php:8.0
      - name: PHP 8.0 local
        run: |
          docker build -f php/8.0/Dockerfile.local -t registry.cn-beijing.aliyuncs.com/baijunyao/php:8.0-local php/8.0/
          docker push registry.cn-beijing.aliyuncs.com/baijunyao/php:8.0-local
      - name: PHP 8.0 production
        run: |
          docker build -f php/8.0/Dockerfile.production -t registry.cn-beijing.aliyuncs.com/baijunyao/php:8.0-production php/8.0/
          docker push registry.cn-beijing.aliyuncs.com/baijunyao/php:8.0-production
  elasticsearch:
    name: Elasticsearch
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - uses: azure/docker-login@v1
        with:
          login-server: registry.cn-beijing.aliyuncs.com
          username: ${{ secrets.ALIYUN_CONTAINER_REGISTRY_USERNAME }}
          password: ${{ secrets.ALIYUN_CONTAINER_REGISTRY_PASSWORD }}
      - name: Elasticsearch 7.4
        run: |
          docker build -f elasticsearch/7.4/Dockerfile -t registry.cn-beijing.aliyuncs.com/baijunyao/elasticsearch:7.4 elasticsearch/7.4/
          docker push registry.cn-beijing.aliyuncs.com/baijunyao/elasticsearch:7.4
      - name: Elasticsearch 7.6
        run: |
          docker build -f elasticsearch/7.6/Dockerfile -t registry.cn-beijing.aliyuncs.com/baijunyao/elasticsearch:7.6 elasticsearch/7.6/
          docker push registry.cn-beijing.aliyuncs.com/baijunyao/elasticsearch:7.6
  ossutil:
    name: OSSUtil
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - uses: azure/docker-login@v1
        with:
          login-server: registry.cn-beijing.aliyuncs.com
          username: ${{ secrets.ALIYUN_CONTAINER_REGISTRY_USERNAME }}
          password: ${{ secrets.ALIYUN_CONTAINER_REGISTRY_PASSWORD }}
      - name: OSSUTIL 1.7.0
        run: |
          docker build -f ossutil/1.7.0/Dockerfile -t registry.cn-beijing.aliyuncs.com/baijunyao/ossutil:1.7.0 ossutil/1.7.0/
          docker push registry.cn-beijing.aliyuncs.com/baijunyao/ossutil:1.7.0
  prometheus:
    name: Prometheus
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - uses: azure/docker-login@v1
        with:
          login-server: registry.cn-beijing.aliyuncs.com
          username: ${{ secrets.ALIYUN_CONTAINER_REGISTRY_USERNAME }}
          password: ${{ secrets.ALIYUN_CONTAINER_REGISTRY_PASSWORD }}
      - name: Prometheus v2.23.0
        run: |
          docker build -f prometheus/2.23.0/Dockerfile -t registry.cn-beijing.aliyuncs.com/baijunyao/prometheus:v2.23.0 prometheus/2.23.0/
          docker push registry.cn-beijing.aliyuncs.com/baijunyao/prometheus:v2.23.0
  grafana:
    name: Grafana
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - uses: azure/docker-login@v1
        with:
          login-server: registry.cn-beijing.aliyuncs.com
          username: ${{ secrets.ALIYUN_CONTAINER_REGISTRY_USERNAME }}
          password: ${{ secrets.ALIYUN_CONTAINER_REGISTRY_PASSWORD }}
      - name: Grafana 7.3.4
        run: |
          docker build -f grafana/7.3.4/Dockerfile -t registry.cn-beijing.aliyuncs.com/baijunyao/grafana:7.3.4 grafana/7.3.4/
          docker push registry.cn-beijing.aliyuncs.com/baijunyao/grafana:7.3.4
  notify:
    name: Slack Notify
    runs-on: ubuntu-latest
    needs: [ubuntu, alpine, mysql-client, nginx, mysql, php, elasticsearch, ossutil, prometheus, grafana]
    if: always()
    steps:
      - name: Slack Notify
        uses: baijunyao/action-slack-notify@v3.0.0
        if: always()
        with:
          slack_channel_id: CMRA2NF3L
          slack_bot_token: ${{ secrets.SLACK_BOT_TOKEN }}
          github_context: ${{ toJson(github) }}
